### ISSUE TITLE
`saved_models` are missing

### ISSUE THREAD

**Issue by ozanyetkin** [tejaskhot/primitive_fitting_3d#2]
Hello, @tejaskhot ! 

First off, thanks for sharing your great work! Just wanted to let you know that `saved_models` is missing and it is not possible to test your trained model. If you can share the `saved_models` as you mentioned in the project's readme, I would be glad to test your work and use it in my research.

Thanks in advance!

**Comment by tejaskhot** [comment]
Hi @ozanyetkin, 
I just uploaded the files to the `saved_models` folder in the repo. Apologies for the delay!

**Comment by ozanyetkin** [comment]
Thank you very much! @tejaskhot
